### ISSUE TITLE
Add support for Poetry

### ISSUE THREAD

**Issue by Arrrlex** [at-gmbh/at-python-template#10]
I believe it would be great if, as an alternative to pip and conda, this template also supported [poetry](https://python-poetry.org/).

### Advantages
1. Easy project isolation
2. Automatic dependency resolution and reproducible builds
3. Only one config file (pyproject.toml) reduces clutter

### Disadvantages
1. This will increase the complexity of the template
2. It will make the template less opinionated, which makes it less helpful as a tool to bootstrap new python projects

In my opinion, poetry is wholly superior to the traditional approach of pip, setup.py and requirements.txt. Thus, if increasing complexity is a concern, we could try something like:

1. Implement poetry for a specified trial period (e.g. 6 months)
2. At the end of the period, if a few projects have used and liked poetry, remove (or deprecate) the pip option in the template
3. If no projects have used poetry, or people ran into difficulties or disliked it, remove poetry from the template

### Required Work
Here's my assessment of what needs to be done:
1. Add poetry option to `cookiecutter.json`
2. Add `pyproject.toml` template and update `handle_package_manager()` accordingly
3. Create `Dockerfile__poetry` template and update `handle_docker()` posthook accordingly
4. Update `docker-compose.yml` template (behaviour for poetry should be the same as for pip)

Since the editor config files do not point to python executables, there's no need to change them.

I may have missed something; let me know if you notice anything! Thanks 😄

**Comment by klamann** [comment]
I support the idea to add poetry as a third option.
Yes, it will be one more thing that a newcomer may have to think about, but honestly, I blame Python for not making a great package management tool in the first place 😜

Your assessment of the necessary changes looks fine to me. If you want to implement this, please submit a PR, and if you need any help, don't hesitate to ask :)
