### ISSUE TITLE
Delete __main__.py if create_cli = no

### ISSUE THREAD

**Issue by Arrrlex** [at-gmbh/at-python-template#11]
In my opinion, it does not make sense to have a `__main__.py` file if create_cli is set to "no". Since `__main__.py` is used to run python code from the command line, it makes most sense as the entrypoint to an app's CLI. 

The alternative use case is that the app does exactly one thing, in which case the user might not want the overhead of a fully-fledged CLI with `typer`. I would argue that this overhead is worth it in order to encourage good practice. Besides, even if an app starts off by just doing a single thing with zero options, there's no guarantee it'll stay that way!

**Comment by klamann** [comment]
You're right, the `__main__.py` is a relic from one of the early versions of the template where the CLI was always a part of the template. We should only include it if the user wants a CLI.
