### ISSUE TITLE
Template Assestion Error

### ISSUE THREAD

**Issue by naghmehfazeli** [at-gmbh/at-python-template#16]
I tried to set up the cookiecutter template and I get the folowing error after entering the `Project Name`. 
```
cookiecutter https://github.com/at-gmbh/at-python-template
full_name [Jane Doe]: xyz
company_name []: Test Company
email [contact@alexanderthamm.com]: email@provider.com
project_name [My Project]: Test Project 
Traceback (most recent call last):
  File "/usr/bin/cookiecutter", line 11, in <module>
    load_entry_point('cookiecutter==1.6.0', 'console_scripts', 'cookiecutter')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/usr/lib/python2.7/dist-packages/cookiecutter/main.py", line 82, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/prompt.py", line 216, in prompt_for_config
    val = render_variable(env, raw, cookiecutter_dict)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/prompt.py", line 170, in render_variable
    template = env.from_string(raw)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateAssertionError: no filter named 'slugify'
```

**Comment by Arrrlex** [comment]
Hi Nagmeh. Could you show me which version of cookiecutter you have installed (`cookiecutter --version`)? It looks like `slugify` was [added to cookiecutter in version 1.7.1](https://github.com/cookiecutter/cookiecutter/releases/tag/1.7.1), so I 
think this problem will be solved by upgrading cookiecutter to the latest version (`pip install -U cookiecutter`).

Although slugify is included in cookiecutter, it's [not yet documented](https://cookiecutter.readthedocs.io/en/latest/advanced/template_extensions.html) so it might be worth adding slugify as an explicit extension in `cookiecutter.json`. What do you think, @klamann ?

**Comment by klamann** [comment]
@naghmehfazeli yes, this should be solved with a cookiecutter upgrade. Please upgrade with `conda update -c conda-forge cookiecutter` or `pip install -U cookiecutter`

@Arrrlex I remember that there was a reason why I didn't add the extension to `cookiecutter.json` when we started using `slugify`, but I could be mistaken. We can look into this again, if you think it may be helpful.

We most definitely should add a troubleshooting section to the readme, because the issue of an outdated cookiecutter version has come up before.

**Comment by sbunzel** [comment]
@naghmehfazeli, the template also requires Python >= 3.6, it seems like you are currently using 2.7.

**Comment by naghmehfazeli** [comment]
That doesn't seem right. I am inside a conda environment with python 3.7.6! Shouldn't the cookiecutter use that?

**Comment by naghmehfazeli** [comment]
I had some problems in my setup. 
The last version of cookiecutter was not installed inside my conda environment. I fixed that and now everything is working fine. 
thanks

**Comment by sbunzel** [comment]
Cool, thanks for reporting back, @naghmehfazeli!

**Comment by Arrrlex** [comment]
> @Arrrlex I remember that there was a reason why I didn't add the extension to `cookiecutter.json` when we started using `slugify`, but I could be mistaken. We can look into this again, if you think it may be helpful.

A troubleshooting section sounds like the right thing to do to me :)
