### ISSUE TITLE
Save Traffic Insights after 2 weeks with github action

### ISSUE THREAD

**Issue by SimonCW** [at-gmbh/at-python-template#22]
To check whether our template is used (throughout the company) it could be useful to save the traffic insights beyond the 2 week period. This could be done via an Github Action: https://github.com/sangonzal/repository-traffic-action

Where to store the data? Options: 
- private git repo (it's only csv's)
- S3 company tennant

**Comment by sbunzel** [comment]
cc @Arrrlex

**Comment by klamann** [comment]
I'm in favor of a private git repo under https://github.com/at-gmbh/ - access should be easier to manage

**Comment by Arrrlex** [comment]
Hey @SimonCW , this looks really great! I tried to do the same thing locally using curl, and I ran into permissions issues, but perhaps I did something wrong. I agree that a private git repo is the best option.

**Comment by SimonCW** [comment]
Hey @Arrrlex, I think you would have needed a personal access token to run it locally. I haven't done anything yet except for creating the issue and researching the Github action. So if you want, feel free to jump on it, I'd be happy to support.

**Comment by sbunzel** [comment]
This would be really cool to have! @SimonCW, would you like to pick this up again?
