### ISSUE TITLE
Add CI Pipeline Templates

### ISSUE THREAD

**Issue by klamann** [at-gmbh/at-python-template#3]
Add CI pipeline templates for a few popular CI systems (GitHub Actions, Azure Pipelines, GitLab CI, Travis CI, CircleCI, ...?) and add an option to `cookiecutter.json` to select your CI provider.

**Comment by sbunzel** [comment]
Now that we have a template for GitLab CI and the option to choose a CI provider is set up (thanks @carsten-bo!), should we close this? Or at least make it specific wrt which CI system to add a template for next? @klamann, what do you think?

**Comment by klamann** [comment]
yeah, I agree. I've created #44 for GitHub Actions; if there is interest in other CI systems, we should create separate issues. No reason to leave this open until every CI platform out there is covered ;)
