### ISSUE TITLE
.gitlab-ci.yml not created

### ISSUE THREAD

**Issue by MichaelGehring** [at-gmbh/at-python-template#48]
Unfortunately the blueprint for the ci-pipeline is not created even though I selected `Select ci_pipeline: 2 - gitlab`. 
All the selections I made when using the template:
![choices](https://user-images.githubusercontent.com/65157491/115528079-fe93f880-a291-11eb-8158-941c8afd2fef.png)
The created project structure:
![my-project-structure](https://user-images.githubusercontent.com/65157491/115528187-19ff0380-a292-11eb-8d00-018a9487d233.png)

**Comment by klamann** [comment]
let me guess: your file manager did not display hidden files? ;)

we should add a troubleshooting section [in the wiki](https://github.com/at-gmbh/at-python-template/wiki) and document stuff like that.
