### ISSUE TITLE
When wrong syntax in project slug, necessary to start the script from the beginning

### ISSUE THREAD

**Issue by andriimazur93** [at-gmbh/at-python-template#57]
I have noticed that when the project slug has forbidden characters, it is necessary to start the script again and unfortunately all the provided selections are lost. 

I have a suggestion: it is possible to checked the project slug directly after the user has entered it, if there are errors, then the appropriate message will be shown, and a user has an opportunity to correct the error.

@klamann If that's fine, I could work on this issue.
![image](https://user-images.githubusercontent.com/22343598/177493847-dcf75396-f381-4d69-b283-889f9f935951.png)

**Comment by ncbkr** [comment]
It does not seem to be possible to interactively (right after entering a value) validate it and prompt again in case it is invalid. The prompts are implemented [here](https://github.com/cookiecutter/cookiecutter/blob/f9376a96097086476ce9eb0b93297a471ae520e0/cookiecutter/prompt.py#L178). After being read, they are immediately stored in a config dict and there is no option to inject any validation code.

To make fixing and rerunning a smoother experience, I can imagine doing the following.

1. in [pre_gen_project.py](https://github.com/at-gmbh/at-python-template/blob/531e7d6119474c2d2cdd6537f7972416de7d7e50/hooks/pre_gen_project.py#L37), we create a replay-file containing all the user inputs in case a validation fails (or copy the one that  cookiecutter created). The arguments that failed the validation get a `FIXME` comment
2. the error message shown to the user contains a hint on how to use the exported config file to render the template, e.g.: `cookiecutter . --replay --replay-file <path to replay file>`

any thoughts @klamann ?

**Comment by ncbkr** [comment]
Or even simpler, we just hint where the user finds the default replay file and tell him to run `cookiecutter . --replay` after fixing
